language: node_js

node_js:
  - "6.11.2"

cache:
  directories:
    - sysconfcpus

before_install:
  - npm i -g elm webpack

install: 
  - npm install
  - elm-package install -y
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

before_script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 webpack
